### ISSUE TITLE
Using klippy in HTML presentations

### ISSUE THREAD

**Issue by mattwarkentin** [RLesur/klippy#16]
Hi @RLesur,

This is a great package. However, I can't seem to get `klippy` working for HTML presentations generated using `xaringan`. I also tried other `Rmd` HTML presentation formats like `ioslides_presentation` and `slidy_presentation` and neither work. I have followed the basic instructions but no clipboard button appears in the presentation even when viewing in a compatible browser. Is there a way to use `klippy` in an HTML presentation?

Thanks for your help.

Matt

**Comment by RLesur** [comment]
Hi @mattwarkentin,
Thanks for the compliment!
Supporting HTML presentations requires interacting with third parties JS libraries. I have no idea of the amount of work. I'll have a look.

**Comment by mattwarkentin** [comment]
Hi @RLesur,

Thanks for the prompt response. What are the technical differences between an HTML presentation and an HTML document that makes this so? Just wondering for my own personal interests. Thanks for looking into it, and I will do the same.

**Comment by RLesur** [comment]
An HTML document is mainly composed of raw HTML.
All HTML slideshows use some JS libraries to compose the slides: the main subject is to sync these libraries with the klippy script. For instance, xaringan uses [remark](https://github.com/gnab/remark) to build the HTML slides directly from markdown. Therefore, the addition of the clipboard buttons can only be done after that remark has finished to build the HTML content.
For each HTML slideshow format, we need to dive into the specific JS library used by this format to understand how to sync the different JS scripts. 
In general, it is possible, it only takes time to implement it correctly.

**Comment by mattwarkentin** [comment]
Ahh, I see! Thank you for taking the time to explain this. It makes sense now why this implementation is not trivial.

**Comment by RLesur** [comment]
In case you are interested in, here is how I've implemented the copy button in bookdown's gitbook https://github.com/rstudio/bookdown/pull/776

**Comment by mattwarkentin** [comment]
Thanks for sharing! I'm comfortable with HTML and CSS but always happy to learn more about how to integrate JS libraries into R packages.

**Comment by mattwarkentin** [comment]
As a follow-up, how come the "copy to clipboard" button is different between `pkgdown` websites and standard HTML documents (rendered from a `Rmd`). For example, in a `pkgdown` site the aesthetics are quite different (i.e. button is larger, different icon, only appears when hovering the code block, etc.). Are these differences controlled by the CSS?

Sorry if my questions are bothersome. I'm just interested.

**Comment by RLesur** [comment]
No problem, I like to share things I love to play with!

As all the **pkgdown** themes use the [bootstrap](https://getbootstrap.com/) and [Font Awesome](https://fontawesome.com/) libraries, the copy button takes benefit of those:
https://github.com/r-lib/pkgdown/blob/134033d9d744c548c6fbe297bc0fbd1a2f498e83/inst/assets/pkgdown.js#L86
The classes chosen for this button is `btn btn-primary btn-copy-ex`: this defines the icon size and ensures that the color is picked from the theme chosen by the user.
The shape comes from Font Awesome (`<i class='fa fa-copy'></i>`).
The hovering behavior is controlled with CSS here: https://github.com/r-lib/pkgdown/blob/134033d9d744c548c6fbe297bc0fbd1a2f498e83/inst/assets/pkgdown.css#L203-L219

In klippy, I didn't want to constraint the user to use a framework (klippy is "framework agnostic"). But I have to admit that once a framework is chosen one can add a button that suits well with it.

**Comment by mattwarkentin** [comment]
Thanks @RLesur  for taking the time to share that information. Again, it was very helpful. It led me down a path of changing the `klippy` aesthetic.

Using the CSS classes in `klippy/inst/htmldependencies/lib/klippy-0.0.0.9500/css/klippy.css`, I was able to use `htmltools::includeCSS()` to add my own stylesheet to the HTML document and was more-or-less able to recreate a `pkgdown`-like copy button. I wasn't able to replicate the look and functionality exactly, but thats mostly due to my own shortcomings with CSS/JS.

**Comment by dcousin3** [comment]
@mattwarkentin I would be interested to know how you succeeded in inserting a pgkdown-like copy button in slide presentations. This is really a feature missing.
