### ISSUE TITLE
klippy not on the top left

### ISSUE THREAD

**Issue by emdelponte** [RLesur/klippy#8]
@RLesur thank you for putting together such a nice package. I can't make it position at the very top left. Perhaps an issue with the css of the academic theme?

My page:
https://www.openplantpathology.org/notes/sparks/1/

Css code:
https://github.com/openplantpathology/OpenPlantPathology/blob/master/public/styles.css

pre,code { 
  font-family: 'Roboto Mono', monospace;
  font-size: 16px;
  color:black;
  background-color: #f9f2f4;
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}

pre {
  margin: 0 0 1rem 0;
  overflow: auto;
  background-color: rgb(248, 248, 248); /* Match default highlight theme. */
  border-color: rgb(220, 248, 248);
}

**Comment by RLesur** [comment]
@emdelponte Thanks for using `klippy` and submit an issue! 
Your link helped me a lot to find the problem. I don't think it comes from the academic theme. 
I think it can be resolved in `klippy` css itself. I need some hours to fix it.

**Comment by RLesur** [comment]
@emdelponte I fixed the css. Can you try with the new version of `klippy` and tell me if this is ok for you?

**Comment by emdelponte** [comment]
@RLesur fixed! thank you. I tweaked the CSS of the theme to put more space around the icon from the top. I noticed the icon changes size according to padding-left. Here is how I did:

`pre {
    padding-top:30px;
    padding-left:15px;}
`

The final result:
https://www.openplantpathology.org/notes/sparks/1/

I wonder if it would be possible for the user to set the position of the icon as top-right, top-left, bottom-left, etc. My intuition is to look for the button on the top-right position.

**Comment by RLesur** [comment]
@emdelponte Yes, the icon width depends on the padding-left (see [here](https://github.com/RLesur/klippy/blob/a68ae53cf9c117f5659c8400df310868e370a5a6/inst/htmldependencies/lib/klippy-0.0.0.9500/js/klippy.js#L53)).  
With a `padding-left` of `15px`, you can reduce the `padding-top` to `23px`.

About the icon position, my very first draft set the icon at the top-right corner. However, nobody saw it and I was a little bit disappointed. @elinw explained me that studies show that the eyes first scroll at the upper left corner. So, I chose it. It is possible to develop a new feature to let the user choose the position. I will open a feature request.  
You can right now test a top-right position with the following `CSS`:  

    pre.sourceCode {
      padding-top: 23px;
      padding-right: 15px;
    }
    .btn-klippy {
      left: auto!important;
      right: 0;
    }

**Comment by emdelponte** [comment]
Thanks! Nice enhancement. You are right, the small icon at the top right may be missed easily. I noticed also when viewing in smartphone screen where the user need to scroll horizontally to see the icon. I am happy with the icon at the left bottom. For long codes, user does not need to scroll up to copy it. How about setting the color for the icon?

**Comment by RLesur** [comment]
@emdelponte For the color, my first choice was to pick the link color for a `<a>` element. I think I can enhance the package in order to choose a color. I will open a FR.

**Comment by RLesur** [comment]
@emdelponte You can now choose a custom `R` color!
